config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :events
  devise_scope :user do
  get 'users/sign_in' => 'users/sessions#new', as: 'sign_in'
  get 'users/sign_up' => 'users/registrations#new',  as: 'sign_up'
  get '/users/sign_out' => 'users/sessions#destroy', as: 'sign_out'
  end

  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:create]
  resources :home
  resources :profiles 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
     
      if user.role == "admin"
        can :manage, :all
      elsif user.role == "editor"
       
        can [:update,:delete], Article do |article|
        
           article.editor_id == user.id
        end    
        can [:create, :update], Comment
        can [:create, :update], Event
        can :read , :all 
      else
        can :read, :all
        can :create, Comment
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, as: :commentable
	belongs_to :user ,foreign_key: "editor_id"
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
	belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :pic, styles: { medium: "300x300>", thumb: "30x20>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\z/
  
  has_one :user
  has_one :user_address
  accepts_nested_attributes_for :user_address, reject_if: :all_blank, allow_destroy: true
  
 
end

app/models/user_address.rb
class UserAddress < ApplicationRecord

	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
  #load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, notice: exception.message 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
load_and_authorize_resource
	before_action :set_article, only: [:edit, :update, :destroy, :show]
  
  def index
  	@articles = Article.all
  end
	def new
		@article = Article.new 
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to articles_path, notice: "article saved successfully"
		else
	    render :new
		end
	end
	 
	def edit
		
	end
  def show
  	
  end

	def update
		if @article.update(article_params)
			redirect_to article_path(@article), notice: "article update successfully"
    else
      render :edit
    end

	end

	def destroy
		
		if @article.destroy
			redirect_to articles_path, notice: "article deleted successfully"
		else
			redirect_to articles_path
		end

	end



	private

		def article_params
			params.require(:article).permit(:name, :published, :description, :editor_id)
		end

		def set_article
			@article = Article.find(params[:id])
		end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	load_and_authorize_resource

def create
	 @comment.save
    redirect_to @comment.commentable
end

private

def comment_params

params.require(:comment).permit(:user_id, :commentable_type, :commentable_id,
	:description)
	
end

end	

app/controllers/events_controller.rb
class EventsController < ApplicationController
   load_and_authorize_resource #load_resource it loads current resource
   #authorize_resource calls the ability class

	def index
		#@events = Event.all //by default it loads everything
	end
  
  def new
  end

	def create
		if @event.save
			redirect_to events_path, notice:"your event details saved successfully completed..!"

		else
		  render :new ,notice:"wrong details entered ...!"
		end	
		
	end

	def edit
		
	end

  def show
  	@comment = @event.comments.build
  end

	def update

		if @event.update(event_params) 
      redirect_to @event, notice: "updated successfully"
			else
      render :edit
			end
		
	end

	def destroy 
		@event.destroy
		respond_to do |format|
		  format.js 
		end
		# if @event.destroy
  #    redirect_to events_path, notice: "event deleted successfully"
  #   else
  #   	redirect_to events_path, notice: "not deleted"
  #   end

	end

	private

	def event_params
		params.require(:event).permit(:name,:date,:address,:description)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
	
end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	before_action :set_user , only: [:edit, :update]
	def index
		
	end
  
  def edit
 
   @user.build_user_address unless @user.user_address
  end

	def update
 
  if	@user.update(user_params)
    binding.pry
    redirect_to profiles_path, notice: "successfully update your profile"
  else
    render :edit
  end
 
	end

	 private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, 
      :dob, :pic, user_address_attributes: [:id, :door_no, :city, :street,
       :state, :pincode])
  end	

  def set_user
  	@user = User.find(params[:id])
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

 def create
 	@user = User.new(user_params)
 	if @user.save
 		redirect_to sign_in_path, notice: "signed up successfully...!"
  else 
 		render :new
 end
 end
 def update
 		if @user.update(user_params)
 		redirect_to profile_path, notice: "user details updated successfully...!"
  else 
 		render :edit
 end
 end
 private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :dob, :pic)
  end

end	

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController


def new
	super
end

def create
	super
	
end
 

def destroy
 
	super	

end

end	

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<table>
	<%= f.hidden_field :editor_id, value: current_user.id  %>
	<tr> <td>Name </td> <td> <%= f.text_field :name ,:onkeypress=>"return isNumberKey(event)"%> </td></tr>
	<tr> <td>description </td> <td> <%= f.text_area :description %> </td></tr>
	<tr> <td> is published: </td> <td> <%= f.check_box :published	 %> </td></tr>
	<tr><td> <%= f.submit 'save' %></td></tr>
 

</table>

<% end %>

app/views/articles/edit.html.erb
<%= render 'articles/form' %>

app/views/articles/index.html.erb
<%= link_to 'add article', new_article_path %>

<table width="100%">
	<th>Name</th>
	<th>description</th>
	<th>published</th>
		<th>editor</th>
		<th>Actions</th>

<% @articles.each do |article| %>
		<tr>
			<td> <%= article.name %></td>
      <td> <%= article.description %></td>
      <td> <%= article.published? ? "Yes": "No" %></td>
      <td> <%= article.user.email %></td>
      <td> <%= link_to 'shows', article_path(article) %>

      <% if can? :update, article %>
           <%= link_to 'edit', edit_article_path(article) %>
           <%= link_to 'delete',article, method: :delete, data: {confirm: 'are you sure?'}  %>
      <% end %>     
      </td>
		</tr>
<% end %>		
</table>

app/views/articles/new.html.erb
<%= render 'articles/form' %>

app/views/articles/show.html.erb
<table>
	<tr><td> Name </td>
  <td> <%= @article.name %> </td>
	</tr>
		<tr><td> Description </td>
  <td> <%= @article.description %> </td>
	</tr>
		<tr><td> editor </td>
  <td> <%= @article.user.email %> </td>
	</tr>
		<tr><td> is Published </td>
  <td> <%= @article.published? ? "yes" : "no" %> </td>
	</tr>
</table>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
<div class="row"> 
 
<label> Name </label>
<%= f.text_field :name %>
 
</div>
<br/>
<div class="row"> 
 
<label> Date </label>
<%= f.text_field :date %>
 
</div>
<br/>
<div class="row"> 
 
<label> Description </label>
<%= f.text_area :description %>
 
</div>
<br/>
<div class="row"> 
 
<label> Address </label>
<%= f.text_area :address %>
 
</div>
<br/>
<div class="row"> 
<%= f.submit 'save' %>
</div>
<% end %>

app/views/events/destroy.js.erb
$('#event_<%= @event.id %>').remove();

app/views/events/edit.html.erb
<%= render 'events/form' %>

app/views/events/index.html.erb
<div class="row" style="float:right">
<%= link_to 'add event',new_event_path %>

</div>

<table width="100%">
	
	<tr>

	<th> Name</th>
	<th> Date</th>
	<th> Description</th>
	<th> Actions</th>

	</tr>

<% @events.each do |event| %>

<tr id="event_<%= event.id %>">
<td> <%= event.name %></td>
<td> <%= event.date %></td>
<td> <%= event.description %></td>
<td>
<%= link_to 'show', event_path(event) %>
 <%= link_to 'edit', edit_event_path(event) %>
     <%= link_to 'delete', event, method: :delete, data: {remote: true,confirm: 'are you sure?'}  %>
     
 </td>
</tr>


<% end %>

</table>

app/views/events/new.html.erb
<%= render 'events/form' %>

app/views/events/show.html.erb
<table>
	
	<tr> <td> Name  :</td> <td> <%= @event.name %></td></tr>
		<tr> <td> Date :</td> <td> <%= @event.date %></td></tr>
			<tr> <td> Description :</td> <td> <%= @event.description %></td></tr>
				<tr> <td> Address :</td> <td> <%= @event.address %></td></tr>
</table>

<%= form_for @comment do |f| %>
<table>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :commentable_id, value: @comment.commentable_id %>
	<%= f.hidden_field :commentable_type, value: @comment.commentable_type %>
	<tr> <td> Comment</td><td> <%= f.text_area :description %> </td> </tr>
	<tr> <td> </td><td> <%= f.submit 'post' %>  </td> </tr>
</table>
<% end %>

<table>
<% @event.comments.each do |comment| %>
  <% if comment.id %>
	<tr>  <td> <%= comment.description %> &nbsp;by </td> 
        <td>  <%= comment.user.email %></td>
	  </tr>
	  <% end %>
	<% end %>
</table>

app/views/profiles/edit.html.erb
<%= form_for @user, :url=>profile_path do |f| %>
<div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.text_field :dob, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :pic %><br />
    <%= f.file_field :pic %>
  </div>
  <%=  f.fields_for  :user_address do |address| %>
       <div class="field">
        <%= address.label :door_no %><br />
        <%= address.text_field :door_no %>
      </div>
          <div class="field">
        <%= address.label :street %><br />
        <%= address.text_field :street %>
      </div>
         <div class="field">
        <%= address.label :city %><br />
        <%= address.text_field :city %>
      </div>
          <div class="field">
        <%= address.label :state %><br />
        <%= address.text_field :state %>
      </div>
          <div class="field">
        <%= address.label :pincode %><br />
        <%= address.text_field :pincode %>
      </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/profiles/index.html.erb
<table>
	<tr>
		<td> email</td>
		<td> <%= current_user.email %> </td> 
	</tr>
	<tr>
		<td> dob</td>
		<td> <%= current_user.dob %> </td> 
	</tr>
	<tr>
		<td> pic</td>
		<td> <%= image_tag current_user.pic.url(:thumb) ,:style=>"height:80px;width:80px"%> </td> 
	</tr>
	<tr>
	<td></td>
	<td> <%= link_to 'edit profile', edit_profile_path(current_user.id) %> </td>
	</tr>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>