config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :events
  devise_scope :user do
  get 'users/sign_in' => 'users/sessions#new', as: 'sign_in'
  get 'users/sign_up' => 'users/registrations#new',  as: 'sign_up'
  get '/users/sign_out' => 'users/sessions#destroy', as: 'sign_out'
  end

  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:create]
  resources :home
  resources :profiles 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
     
      if user.role == "admin"
        can :manage, :all
      elsif user.role == "editor"
       
        can [:update,:delete], Article do |article|
        
           article.editor_id == user.id
        end    
        can [:create, :update], Comment
        can [:create, :update], Event
        can :read , :all 
      else
        can :read, :all
        can :create, Comment
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, as: :commentable
	belongs_to :user ,foreign_key: "editor_id"
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
	belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :pic, styles: { medium: "300x300>", thumb: "30x20>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\z/
  
  has_one :user
  has_one :user_address
  accepts_nested_attributes_for :user_address, reject_if: :all_blank, allow_destroy: true
  
 
end

app/models/user_address.rb
class UserAddress < ApplicationRecord

	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
  #load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, notice: exception.message 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
load_and_authorize_resource
	before_action :set_article, only: [:edit, :update, :destroy, :show]
  
  def index
  	@articles = Article.all
  end
	def new
		@article = Article.new 
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to articles_path, notice: "article saved successfully"
		else
	    render :new
		end
	end
	 
	def edit
		
	end
  def show
  	
  end

	def update
		if @article.update(article_params)
			redirect_to article_path(@article), notice: "article update successfully"
    else
      render :edit
    end

	end

	def destroy
		
		if @article.destroy
			redirect_to articles_path, notice: "article deleted successfully"
		else
			redirect_to articles_path
		end

	end



	private

		def article_params
			params.require(:article).permit(:name, :published, :description, :editor_id)
		end

		def set_article
			@article = Article.find(params[:id])
		end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	load_and_authorize_resource

def create
	 @comment.save
    redirect_to @comment.commentable
end

private

def comment_params

params.require(:comment).permit(:user_id, :commentable_type, :commentable_id,
	:description)
	
end

end	

app/controllers/events_controller.rb
class EventsController < ApplicationController
   load_and_authorize_resource #load_resource it loads current resource
   #authorize_resource calls the ability class

	def index
		#@events = Event.all //by default it loads everything
	end
  
  def new
  end

	def create
		if @event.save
			redirect_to events_path, notice:"your event details saved successfully completed..!"

		else
		  render :new ,notice:"wrong details entered ...!"
		end	
		
	end

	def edit
		
	end

  def show
  	@comment = @event.comments.build
  end

	def update

		if @event.update(event_params) 
      redirect_to @event, notice: "updated successfully"
			else
      render :edit
			end
		
	end

	def destroy 
		@event.destroy
		respond_to do |format|
		  format.js 
		end
		# if @event.destroy
  #    redirect_to events_path, notice: "event deleted successfully"
  #   else
  #   	redirect_to events_path, notice: "not deleted"
  #   end

	end

	private

	def event_params
		params.require(:event).permit(:name,:date,:address,:description)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
	
end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	before_action :set_user , only: [:edit, :update]
	def index
		
	end
  
  def edit
 
   @user.build_user_address unless @user.user_address
  end

	def update
 
  if	@user.update(user_params)
    binding.pry
    redirect_to profiles_path, notice: "successfully update your profile"
  else
    render :edit
  end
 
	end

	 private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, 
      :dob, :pic, user_address_attributes: [:id, :door_no, :city, :street,
       :state, :pincode])
  end	

  def set_user
  	@user = User.find(params[:id])
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController


def new
	super
end

def create
	super
	
end
 

def destroy
 
	super	

end

end	

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <div id="footer">
  <div class="col-xs-4"> </div>
  <div class="col-xs-4">All rights reserved by ...Anil!</div>
  </div> 
  <script language="javascript">
function passwordChanged() {
	 

	var strength = document.getElementById("strength");
	var strongRegex = new RegExp("^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*\W).*$", "g");
	var mediumRegex = new RegExp("^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");
	var enoughRegex = new RegExp("(?=.{6,}).*", "g");
	var pwd = document.getElementById("user_password");
	if (pwd.value.length==0) {
	strength.innerHTML = 'Type Password';
	} else if (false == enoughRegex.test(pwd.value)) {
	strength.innerHTML = 'More Characters';
	} else if (strongRegex.test(pwd.value)) {
	strength.innerHTML = '<span style="color:green">Strong!</span>';
	} else if (mediumRegex.test(pwd.value)) {
	strength.innerHTML = '<span style="color:orange">Medium!</span>';
	} else {
	strength.innerHTML ='<span style="color:red">Weak!</span>';
	}
}
</script>

app/views/layouts/_header.html.erb
<div id="header">
<div class="row">
	<div class="col-xs-4"> LOGO</div>
	<div class="col-xs-4">
	  <% if current_user.present? %> 
	 welcome to <%=current_user.email %>! 
	                         <%=image_tag current_user.pic.url(:thumb) ,:style=>"height:20px;width:40px"%>
	                            <% else %>
	                            
	                        <% end %> 
	 </div>

	<div class="col-xs-4">
	 <% if current_user.present? %>
    <%= link_to 'Log out', sign_out_path, method: 
	                            "delete" %>
	                            <% end %>	
	 </div>
</div>
 <% if current_user.present? %>
<div class="row">

<li>
	
	<ul>
	  <li><a href="/profiles"> My Profile </a></li>
		<li> <a href="/events">Event</a> </li>
		<li><a href="/articles"> Article </a></li>
	</ul>
</li>

</div>

<% end %>
  </div>
  <br/><br/><br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
 

  <body>

  <%= render 'layouts/header' %>

  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>
  <div>
    <%= yield %>
    </div>
 
 <%= render 'layouts/footer' %>
  </body>
</html>